/**
 * Cloudflare Worker entry for the Firearm Studio SPA.
 *
 * - `/api/*`  → proxied to the backend (env.API_BASE_URL). Keeping the API
 *   same-origin in production avoids CORS, mirroring the Vite dev proxy.
 * - everything else → served from static assets (env.ASSETS), with SPA
 *   fallback to index.html configured in wrangler.jsonc.
 *
 * `Env` is generated by `wrangler types` into worker-configuration.d.ts —
 * do not hand-write it.
 */
export default {
  async fetch(request, env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith("/api/")) {
      const base = env.API_BASE_URL.replace(/\/+$/, "");
      const target = base + url.pathname + url.search;
      // Forward method, headers (incl. Authorization), and body unchanged.
      // Returning the upstream Response streams it back without buffering.
      return fetch(new Request(target, request));
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;
